version: '3.8'

services:
  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka-2
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CLUSTER_ID=cluster-1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG4J_LOGLEVEL=INFO
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka

  backend:
    build:
      context: .
      dockerfile: Dockerfile.application
    container_name: backend-2
    env_file: .env
    ports:
      - "8000:8000"

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: producer-2
    env_file: .env
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer-2
    env_file: .env
    depends_on:
      - kafka

volumes:
  kafka_data: